Repository engboris/stellogen, pull requests merged in 2025-01, with the labels that each got.

#29 Add encoding techniques in guide
  guide/src/SUMMARY.md
  guide/src/exbase.md
  guide/src/hypergraphs.md
  guide/src/integers.md
  guide/src/intro_encoding.md
  guide/src/lambda.md
  guide/src/lintypes.md
  guide/src/nfsa.md
  guide/src/pda.md
  guide/src/seq.md
  guide/src/transducers.md
  guide/src/turing.md
  guide/src/unification.md
  guide/src/untypedlin.md
Labels: documentation

#30 Improve error messages + fixes on typing expressions
  examples/automata.sg
  examples/binary4.sg
  examples/linear_lambda.sg
  examples/mll.sg
  examples/naive_nat.sg
  examples/stack.sg
  examples/syntax.sg
  guide/src/typing.md
  src/lsc/unification.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: bug

#32 Fix printing of constellations and galaxies
  src/lsc/lsc_ast.ml
  src/stellogen/sgen_ast.ml
Labels: bug

#34 Improve guide to make it friendlier
  README.md
  guide/src/SUMMARY.md
  guide/src/encoding/introduction.md
  guide/src/introduction/introduction.md
  guide/src/introduction/start.md
  guide/src/stellarresolution/entities.md
  guide/src/stellarresolution/execution.md
  guide/src/stellarresolution/exercises.md
  guide/src/stellarresolution/unification.md
  guide/src/stellogen/definitions.md
  guide/src/stellogen/galaxies.md
  guide/src/stellogen/typing.md
  src/lsc/lsc_lexer.mll
  src/stellogen/sgen_lexer.mll
Labels: documentation

#36 Change terminology (introduce action and state space)
  guide/en/src/stellarresolution/execution.md
  guide/en/src/stellogen/definitions.md
  guide/fr/src/stellarresolution/execution.md
  guide/fr/src/stellogen/definitions.md
Labels: documentation

#54 Handle lexing errors with positions
  bin/sgen.ml
  src/stellogen/format_exn.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
Labels: enhancement

#55 (hopefully) fix CI on windows
  .github/workflows/build.yml
  bin/sgen.ml
Labels: bug

#52 Remove need for $ symbol
  README.md
  examples/automata.sg
  examples/binary4.sg
  examples/circuits.sg
  examples/lambda.sg
  examples/linear_lambda.sg
  examples/mll.sg
  examples/naive_nat.sg
  examples/nat.sg
  examples/npda.sg
  examples/prolog.sg
  examples/stack.sg
  examples/syntax.sg
  guide/en/src/encoding/introduction.md
  guide/en/src/encoding/seq.md
  guide/en/src/stellarresolution/entities.md
  guide/en/src/stellarresolution/execution.md
  guide/en/src/stellarresolution/exercises.md
  guide/en/src/stellogen/definitions.md
  guide/en/src/stellogen/exercises.md
  guide/en/src/stellogen/galaxies.md
  guide/en/src/stellogen/substitutions.md
  guide/en/src/stellogen/typing.md
  guide/fr/src/encoding/introduction.md
  guide/fr/src/encoding/seq.md
  guide/fr/src/stellarresolution/entities.md
  guide/fr/src/stellarresolution/execution.md
  guide/fr/src/stellarresolution/exercises.md
  guide/fr/src/stellogen/definitions.md
  guide/fr/src/stellogen/exercises.md
  guide/fr/src/stellogen/galaxies.md
  guide/fr/src/stellogen/substitutions.md
  guide/fr/src/stellogen/typing.md
  src/common_tokens.mly
  src/lsc/lsc_ast.ml
  src/lsc/lsc_lexer.mll
  src/lsc/lsc_parser.mly
  src/stellogen/lsc_ast.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
  test/testsuite/automata.sg
  test/testsuite/prolog.sg
Labels: enhancement

#59 Add reactive effect for print
  .ocamlformat-ignore
  src/common_tokens.mly
  src/lsc/format_exn.ml
  src/lsc/lsc_ast.ml
  src/lsc/lsc_lexer.mll
  src/lsc/lsc_parser.mly
  src/stellogen/format_exn.ml
  src/stellogen/lsc_ast.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_parser.mly
Labels: enhancement

#60 Replace print by show-exec and add exec block
  examples/binary4.sg
  examples/circuits.sg
  examples/lambda.sg
  examples/linear_lambda.sg
  examples/mll.sg
  examples/nat.sg
  examples/prolog.sg
  examples/stack.sg
  examples/syntax.sg
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: enhancement

#63 Fix multi-line unions
  examples/syntax.sg
  src/stellogen/sgen_parser.mly
Labels: bug

#68 Add inequality constraints
  examples/syntax.sg
  src/lsc/lsc_ast.ml
  src/lsc/lsc_lexer.mll
  src/lsc/lsc_parser.mly
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: enhancement

#66 Add run declaration (for reactive effects)
  examples/syntax.sg
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: enhancement

#69 Improve debugging with trace and add trace command
  bin/lscrun.ml
  examples/syntax.sg
  src/lsc/lsc_ast.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: enhancement
