Repository engboris/stellogen, pull requests merged in 2025-04, with the labels that each got.

#100 Linear constellations
  bin/lscrun.ml
  examples/mll.sg
  nvim/syntax/stellogen.vim
  src/lsc/lsc_ast.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_eval.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
  test/behavior/automata.sg
  test/behavior/linear.sg
  test/behavior/prolog.sg
Labels: enhancement

#105 Remove sources of unpredictability in behaviour of execution
  examples/linear_lambda.sg
  examples/mll.sg
  examples/syntax.sg
  exercises/solutions/01-paths.sg
  exercises/solutions/04-boolean.sg
  src/lsc/lsc_ast.ml
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_eval.ml
  src/stellogen/sgen_parser.mly
  test/behavior/galaxy.sg
  test/behavior/linear.sg
  test/lsc/basic.stellar
Labels: bug, refactoring, syntax

#106 Add basic file import
  bin/sgen.ml
  examples/syntax.sg
  nvim/syntax/stellogen.vim
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_eval.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
  src/stellogen/sgen_parsing.ml
Labels: enhancement, high priority

#104 Escherichia/syntax for proofs
  examples/syntax.sg
  src/stellogen/sgen_ast.ml
  src/stellogen/sgen_eval.ml
  src/stellogen/sgen_lexer.mll
  src/stellogen/sgen_parser.mly
Labels: enhancement, syntax

#110 Add example of Turing machine
  examples/automata.sg
  examples/prolog.sg
  examples/turing.sg
Labels: play with language
